### ISSUE TITLE
vscode opens the terminal to automatically execute the environment activation command, and opens the cmd window

### ISSUE THREAD

**Issue by WEN0115-L** [microsoft/vscode-python-environments#1122]
Problem:
When creating a new terminal in VSCode (v1.102), it automatically enters the base environment and then automatically executes commands：

D:/Anaconda/Scripts/activate
conda activate ML

causing:

Visible cmd terminal flash
5-10 second startup delay
Occasional freezes

Expected Behavior:

Direct opening in ML environment (instant) without visible commands.

Troubleshooting Attempted:

Toggled python.terminal.activateEnvironment (true/false)
Downgraded to VS Code v1.85 (issue persists)

System & Extension Details:

OS: Windows 11
Conda: v24.11.3 (path: D:/Anaconda)

Explicit Question: What configuration (VSCode/Conda) will open terminals directly in ML without visible activation sequences?

this is my setting.json：
`{
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "workbench.settings.applyToAllProfiles": [
        
    ]
}`

**Comment by WEN0115-L** [comment]
<img width="1920" height="1030" alt="Image" src="https://github.com/user-attachments/assets/ff25552e-d4e8-487d-9113-b316e0843c19" />

**Comment by YuyueminAustin** [comment]
similar problem. The environment is actually not the correct one.

**Comment by WEN0115-L** [comment]
> similar problem. The environment is actually not the correct one.

What does it mean? Can you be more specific?

**Comment by YuyueminAustin** [comment]
> > similar problem. The environment is actually not the correct one.
> 
> What does it mean? Can you be more specific?

There is pop up windows and then the integrated powershell actually does not activate the correct python environment. It keeps in the base.

**Comment by WEN0115-L** [comment]
> > > similar problem. The environment is actually not the correct one.
> > 
> > 
> > What does it mean? Can you be more specific?
> 
> There is pop up windows and then the integrated powershell actually does not activate the correct python environment. It keeps in the base.

However, after my VS Code automatically runs those two activation commands, a pop-up window appears. But my ML virtual environment is indeed activated, no longer the base environment, and the corresponding Python version has also changed. For example, initially, when a new terminal is created, the Python version is 11.3, but after the pop-up window appears due to the automatic execution of the commands, the Python version of the activated ML environment changes to 3.8.
How can I solve this pop-up issue and the problem of executing the activation command myself?

**Comment by WaterMinding** [comment]
I have collided with the same problem.

**Comment by WaterMinding** [comment]
I've encountered this issue before, but it was resolved when I changed this parameter to the path of pwsh.
However, now my parameter is correct, yet the problem has occurred again.

<img width="509" height="83" alt="Image" src="https://github.com/user-attachments/assets/9e92101f-2a75-482d-8568-a8fe8d00d797" />

**Comment by WaterMinding** [comment]
By the way, I think this issue and another issue are reporting the same problem.
https://github.com/microsoft/vscode-python/issues/25336

**Comment by WaterMinding** [comment]
<img width="1035" height="65" alt="Image" src="https://github.com/user-attachments/assets/e74f8c94-18f2-45ff-ac38-c7274131f073" />
Is it related to these two logs?

**Comment by eleanorjboyd** [comment]
Hi! Can you try setting "python.useEnvironmentsExtension" to false in your user settings and see if this makes a difference? It may be connected to this: [microsoft/vscode-python-environments#581](https://github.com/microsoft/vscode-python-environments/issues/581)

**Comment by WaterMinding** [comment]
It doesn't help. I have set "python.useEnvironmentsExtension" to false, but it didn't make a difference.

**Comment by likesnow97** [comment]
I encountered the same problem as you, but I haven't solved it yet. I can only use PyCharm as a substitute for VS Code for now. Fortunately, I haven't encountered this problem when using PyCharm.

**Comment by WaterMinding** [comment]
I have found a way to temporarily eliminate the pop-up cmd window.
My OS is Win11.
In Anaconda\Scripts, there is a file called "activate", which appears to be written as a Bash script.
When Vscode terminal run 'Anaconda/Scripts/activate', it is actually running Anaconda\Scripts\activate instead of Anaconda\Scripts\activate.bat .
So, I moved Anaconda\Scripts\activate to an unrelated directory. 
Now, Vscode terminal actually runs Anaconda\Scripts\activate.bat, and it can activate conda env without a pop-up cmd window.
However, doing this cannot address the root cause, the command " D:/Tools/Anaconda/Scripts/activate" and " conda activate wuziqi" still exist.

<img width="389" height="75" alt="Image" src="https://github.com/user-attachments/assets/783b2e81-a2f4-4c22-9c30-ab163be72290" />

**Comment by eleanorjboyd** [comment]
Can other people confirm setting "python.useEnvironmentsExtension" to false in your user settings does not help to resolve the situation? Im surprised it is happening since the first I am hearing of this issue lines up with the release of the environments extension and otherwise we haven't made any changes

cc @anthonykim1

**Comment by WEN0115-L** [comment]
> <img alt="图像" width="1035" height="65" src="https://private-user-images.githubusercontent.com/167598389/476364339-e74f8c94-18f2-45ff-ac38-c7274131f073.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NDg2MTUsIm5iZiI6MTc1NTg0ODMxNSwicGF0aCI6Ii8xNjc1OTgzODkvNDc2MzY0MzM5LWU3NGY4Yzk0LTE4ZjItNDVmZi1hYzM4LWM3Mjc0MTMxZjA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMlQwNzM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDcxMDcxNDMyZTU2YTQxOGU1ODBlM2NlNTllMGQzM2NkOTA1MjE0Yzc5OTk0OGU1ZjQ1OTljOTYxYmFkMTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CfsdpiR-OUZata1ZOoELVN1bOXz6caQsKragzXsT21o">是不是和这两条日志有关？

Yes, this is my problem: every time I start a new terminal, these two commands are executed automatically, which makes my terminal start slowly.

**Comment by WEN0115-L** [comment]
> Hi! Can you try setting "python.useEnvironmentsExtension" to false in your user settings and see if this makes a difference? It may be connected to this: [microsoft/vscode-python-environments#581](https://github.com/microsoft/vscode-python-environments/issues/581)

It doesn't help. I have set "python.useEnvironmentsExtension" to false, but it didn't make a difference.

**Comment by WEN0115-L** [comment]
> 我遇到了和你一样的问题，但我还没有解决。我现在只能使用 PyCharm 作为 VS Code 的替代品。幸运的是，我在使用 PyCharm 时没有遇到这个问题。

Hello, have you solved it now?

**Comment by WaterMinding** [comment]
@WEN0115-L 

目前在我的机器上，只要更新python插件和python environments插件到最新版本，并且删除Anaconda/Scripts下的activate文件就能解决问题

**Comment by WaterMinding** [comment]
@WEN0115-L 
可以看一下这个issue中较新的一批讨论
https://github.com/microsoft/vscode-python/issues/25316

**Comment by WEN0115-L** [comment]
> [@WEN0115-L](https://github.com/WEN0115-L) 可以看一下这个issue中较新的一批讨论 [microsoft/vscode-python#25316](https://github.com/microsoft/vscode-python/issues/25316)

好的，非常感谢，我去看看。

**Comment by EnochxynL** [comment]
> [@WEN0115-L](https://github.com/WEN0115-L)
> 
> 目前在我的机器上，只要更新python插件和python environments插件到最新版本，并且删除Anaconda/Scripts下的activate文件就能解决问题

我自己创建了一个activate.ps1来实现与activate.bat相同的功能（而activate是留给bash的）
```
. "$PSScriptRoot/../shell/condabin/conda-hook.ps1"
conda activate
```
这样可以直接激活conda的base环境，无需`conda init powershell`。删掉或者替换activate文件是权宜之计，不过还是希望这个bug早日修复，我不希望一直通过破坏留给bash的activate脚本，用来满足powershell的需求。

**Comment by EnochxynL** [comment]
最终我在`settings.json`中创建了powershell别名

```json
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "args": ["-NoExit", "-Command", "Set-Alias 'C:/ProgramData/miniforge3/Scripts/activate' 'C:/ProgramData/miniforge3/shell/condabin/conda-hook.ps1'"]
        }
    }
```

这样不影响bash类终端（如git bash），也让powershell找到正确的初始化脚本，算是比较优雅的解决方案了

**Comment by EnochxynL** [comment]
新问题：如果我这样设置`settings.json`，会导致我的任何`tasks.json`的配置无法使用，因为Powershell无法接收两个`-Command`参数。现在我比任何时候都希望这个Bug早日修复！

**Comment by EnochxynL** [comment]
最终我在`D:\Documents\WindowsPowerShell\profile.ps1`（conda init会影响到的配置文件）添加
`Set-Alias 'C:/ProgramData/miniforge3/Scripts/activate' 'C:/ProgramData/miniforge3/shell/condabin/conda-hook.ps1'`
全局性地设置了别名。唉

**Comment by eleanorjboyd** [comment]
translations:
New problem: If I set up settings.json like this, any of my tasks.json configurations will not work because Powershell cannot receive two -Command parameters. Now more than ever, I hope this bug is fixed soon!


Finally, I added the line `Set-Alias ​​'C:/ProgramData/miniforge3/Scripts/activate' 'C:/ProgramData/miniforge3/shell/condabin/conda-hook.ps1'` to D:\Documents\WindowsPowerShell\profile.ps1 (the profile that conda init affects). This set the alias globally.

**Comment by eleanorjboyd** [comment]
@EnochxynL are you still experiencing a problem or did that resolve it?

**Comment by WEN0115-L** [comment]
> 最终我在（conda init会影响到的配置文件）添加 全局性地设置了别名。唉`D:\Documents\WindowsPowerShell\profile.ps1``Set-Alias 'C:/ProgramData/miniforge3/Scripts/activate' 'C:/ProgramData/miniforge3/shell/condabin/conda-hook.ps1'`

我现在都没有管他了，感觉修复不了，习惯了都，害

**Comment by WEN0115-L** [comment]
> [@EnochxynL](https://github.com/EnochxynL) are you still experiencing a problem or did that resolve it?

The problem still exists on my end, and I still haven't been able to fix it.

**Comment by anthonykim1** [comment]
Does this exist when doing the same `conda activate .. ` from external terminal (not vscode terminal). 

Also try latest insiders + pre-release of env exstension:

Try install https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-python-envs 

Can you update Python extension, Python environment extension to latest and see if you can still repro? 
Also add `  "python.useEnvironmentsExtension": true,` to your settings.json.

**Comment by WEN0115-L** [comment]
> 在外部终端（不是VScode终端）做同样作时，这种情况存在吗？`conda activate .. `
> 
> 还可以试试最新的insiders+env exstension预发布：
> 
> 试着安装 https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-python-envs
> 
> 你能把Python扩展、Python环境扩展更新到最新版本，看看还能不能复制吗？也要增加你的settings.json。` "python.useEnvironmentsExtension": true,`

No, it doesn't happen with the same project and the same Python environment when opened in PyCharm. I will try the method you provided in real time, thank you very much.

**Comment by anthonykim1** [comment]
https://github.com/user-attachments/assets/7b394a64-9464-4932-b017-caa6ef48f054

Just tried to repro by creating conda environment , creating terminal, running Python file, and failed Maybe something in your pwsh profile is triggering cmd launch?
